
= Tupelo: Making Clojure Even Sweeter

== Change Log

.2017-4-26  Version 0.9.38:  *Breaking Change*
- renamed `select-values` -> `map-keys->vals` (ref. puppetlabs.kitchensink.core/select-values)

.2017-1-2  Version 0.9.15:  Moved functions from `tupelo.misc` namespace to `tupelo.string`
- collapse-whitespace
- equals-ignore-spacing
- double-quotes->single-quotes
- single-quotes->double-quotes
- normalize-str
- str->kw
- char-seq
- seq->str
- printable-chars


.2016-9-14  New functions in `tupelo.string` namespace:
- drop
  "Drops the first N chars of a string, returning a string result."

- take
  "Drops the first N chars of a string, returning a string result."

- indent
  "Indents a string by pre-pending N spaces. Returns a string result."

- indent-lines
  "Splits out each line of txt using clojure.string/split-lines, then
  indents each line by prepending N spaces. Joins lines together into
  a single string result, with each line terminated by a single \newline."

.2016-9-14 *Breaking Changes*
- `tupelo.core/any?` renamed to `has-some?` to avoid conflict with new function `clojure.core/any?`
- `tupelo.core/has-none?` added as synonym for `clojure.core/not-any?`

.2016-6-12 Beginning with version 0.9.0 Tupelo will require
- Clojure 1.9.0-alpha5 or later
- Java 1.8

Copyright © 2016 Alan Thompson.

Distributed under the Eclipse Public License, the same as Clojure.

