cooljure
========

## Cool stuff you wish was in Clojure

Leiningen coordinates:

image:http://clojars.org/cooljure/latest-version.svg[ http://clojars.org/cooljure ]

Overview
--------

Have you ever wanted to do something simple but clojure.core doesn't support it? Or, maybe
you are wishing for an enhanced version of a standard function. The goal of Cooljure is to
add support for these convenience features, so that you have a simple way of using either
the enhanced version or the original version.

The goal in using `cooljure.core` is that you can just plop it in any namespace without
having to worry about any conflicts with core functionality. So, both the core functions
and the added/enhanced functions are both available for use at all times. As such, we use
normally use `:refer :all` for cooljure.core in our namespaces:

[source,clojure]
----
(ns my.proj
  (:require ...
            [cooljure.core    :refer :all]
            [cooljure.csv     :as cool-csv]
            [cooljure.parse   :as cool-parse]
            ... ))
----

cooljure.core - Basic functions
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The truth is not ambiguous
^^^^^^^^^^^^^^^^^^^^^^^^^^

Clojure marries the worlds of Java and Lisp. Unfortunately, these two worlds have
different ideas of truth, so Clojure accepts both `false` and `nil` as _false_. Sometimes
you want to coerce logical values into literal _true_ or _false_ values, so we provide a
simple way to do that:

----
(truthy? arg)
  Returns true if arg is logical true (neither nil nor false);
  otherwise returns false.

(falsey? arg)
  Returns true if arg is logical false (either nil or false);
  otherwise returns false. Equivalent to (not (truthy? arg)).
----

Convenience testing seq's
^^^^^^^^^^^^^^^^^^^^^^^^^

These functions aren't in clojure.core, but people keep writing into the mailing list
wondering where they are. Well, now they are available:

----
(any? pred coll)
  For any predicate & collection, returns true if (pred x) is 
  logical true for any x in coll; otherwise returns false. Like
  clojure.core/some, but returns only true or false.

(not-empty? coll)
  For any collection, returns true if coll contains any items; 
  otherwise returns false. Equivalent to (not (empty? coll)).
----

Focus on vectors
^^^^^^^^^^^^^^^^

Clojure's seq abstraction (and lazy seq's) is very useful, but sometimes you just want
everything to stay in a nice, eager, random-access vector. Here is an easy way to build up
a vector result:

----
(conjv coll x)
(conjv coll x & xs)
  For any collection coll and list of values x, appends the x's to 
  collection, always returning the result as a vector.
----
[source,clojure]
----
=> (conjv '(1 2) 3)
[1 2 3]
----

Map manipulation
^^^^^^^^^^^^^^^^

Sometimes you want to extract the keys & values from a map for manipulation or extension
before building up another map (especially useful manipulating default function args).
Here is very handy function for that:

----
(keyvals m)
  For any map m, returns the keys & values of m as a vector, 
  suitable for reconstructing via (apply hashmap (keyvals m)).
----
[source,clojure]
----
=> (keyvals {:a 1 :b 2})
[:b 2 :a 1]
=> (apply hash-map (keyvals {:a 1 :b 2}))
{:b 2, :a 1}
----

Maps are convenient, especially when keywords are used as functions to look up a value in
a map.  Unfortunately, attempting to look up a non-existing keyword in a map will return
nil.  While sometimes convenient, this means that a simple typo in the keyword name will
silently return corrupted data (i.e. nil instead of the desired value.  The two funcitons
`grab` and `grab-in` are dop-in replacements for `get` and `get-in`, except that they will
throw an Exception in the event the keyword is not present in the map:

----
(grab m k)
  A fail-fast version of get. For map m & key k, returns the value v associated
  with k in m.  Throws an exception if k is not present in m.

(grab-in m ks)
  A fail-fast version of get-in. For map m & keys ks, returns the value v
  associated with ks in m, as for (get-in m ks). Throws an exception if the path
  ks is not present in m.
----

Default value in case of Exception
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Sometimes you know an operation may result in an Exception, and you would like to have the
Exception converted into a default value.  That is when you need:

----
(with-exception-default default-val & body)
  Evaluates body & returns its result.  In the event of an exception the
  specified default value is returned instead."
----

Expression debugging
~~~~~~~~~~~~~~~~~~~~

Ever been debugging some new code and had trouble inserting printing out intermediate
values?  For example:

[source,clojure]
----
(-> 1
    (inc)
    (* 2))
4
----
Suppose you want to disply the value after the (inc) function. You can't just insert a
(println) because the return value of `nil` will break the pipeline structure. Instead,
just use `spy-first`:

[source,clojure]
----
(-> 1
    (inc)
    (spy-first "after inc")
    (* 2))
after inc => 2
4
----
This tool is named `spy-first` since it is intended to be placed into a "thread-first"
pipeline (e.g. using `->` or similar). A companion named `spy-last` is available for
pipelines using "thread-last" (e.g. `->>`):

[source,clojure]
----
(->> 1
    (inc)
    (spy-last "after inc")
    (* 2))
after inc => 2
4
----

Sometimes you may prefer to print out the expression itself, or nothing at all. Then, just
use `spy-expr` or `spy-val`:

[source,clojure]
----
(as-> 1 x
      (spy-expr (inc x))
      (* 2 x))
(inc x) => 2
4

(->> 1
     (inc)
     (spy-val)
     (* 2))
2
4
----
To be precise, the function signatures are:

[source,clojure]
----
(spy-first expr msg )
(spy-last  msg  expr)
(spy-expr  expr)
(spy-val   expr)
----

REPL driven testing
~~~~~~~~~~~~~~~~~~~

Developing at the REPL is productive & cool, but it can be a pain to reload source files
modified in an external editor.  This is especially so when simultaneously editing both
the core program and the corresponding test code.  The function `test-all` will reload
both a namespace and its corresponding test namespace from file, then invoke the corresponding
test namespace:

----
(test-all & ns-list)
  Convenience fn to reload a namespace & the corresponding test namespace from
  disk and execute tests i the REPL.  Assumes canonical project test file
  organization with parallel src/... & test/... directories, where a '-test'
  suffix is added to all src namespaces to generate the cooresponding test
  namespace.  Example:

    (test-all 'cooljure.core 'cooljure.csv)

  This will reload cooljure.core, cooljure.core-test, cooljure.csv,
  cooljure.csv-test and then execute clojure.test/run-tests on both of the test
  namespaces.
----

Floating Point Number Comparison
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Everyone know that you shouldn't compare floating-point numbers (e.g. float, double, etc) for equality since roundoff errors can prevent a precise match between logically equivalent results.  However, it has always been awkward to regenerate "approx-equals" code by hand every time new project requires it.  Here we have a simple function that compares two floating-point values (cast to double) for equality by specifying either the number of significant digits that must match or the maximum error tolerance allowed:

----
(defn rel= val1 val2 & {:as opts} )
  Returns true if 2 double-precision numbers are relatively equal, else false.
  Relative equality is specified as either (1) the N most significant digits are
  equal, or (2) the absolute difference is less than a tolerance.  Input values
  are coerced to double before comparison."
----
An extract from the unit tests illustrates the use of `rel=`
[source,clojure]
----
  (is      (rel= 123450000 123456789 :digits 4 ))
  (is (not (rel= 123450000 123456789 :digits 6 )))

  (is      (rel= 1 1.001 :tol 0.01 ))
  (is (not (rel= 1 1.001 :tol 0.0001 )))
)
----

cooljure.csv - Functions for using CSV (Comma Separate Value) files
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

TEMP TODO:  see source code http://github.com/cloojure/cooljure/blob/master/src/cooljure/csv.clj[cooljure.csv]

coojure.parse - Functions to ease parsing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

TEMP TODO:  see source code http://github.com/cloojure/cooljure/blob/master/src/cooljure/parse.clj[cooljure.parse]
