

= Making Clojure Even Sweeter

Leiningen coordinates:   

image:http://clojars.org/tupelo/latest-version.svg[ http://clojars.org/tupelo ]

=== API Docs:   http://cloojure.github.io/doc/tupelo/

== Overview

Have you ever wanted to do something simple but clojure.core doesn't support it? Or, maybe
you are wishing for an enhanced version of a standard function. The goal of Tupelo is to
add support for these convenience features, so that you have a simple way of using either
the enhanced version or the original version.

=== Tupelo Datomic

A library of helper functions for Datomic. Please see link:src/tupelo/datomic.adoc[the Tupelo Datomic docs]

=== Tupelo Core

A library of helper functions for core Clojure. Please see link:src/tupelo/core.adoc[the Tupelo Datomic docs]

=== Tupelo Explicit - Explicit Language for Clojure

link:src/tupelo/explicit.adoc[Documentation for tupelo.explicit]

=== tupelo.csv - Functions for using CSV (Comma Separate Value) files

The standard link:http://github.com/davidsantiago/clojure-csv[clojure-csv library] has well-tested
and useful functions for parsing CSV (Comma Separated Value) text data, but it does not offer all of
the convenience one may wish. Tupelo CSV emphasizes the idomatic Clojure usage of data, using
sequences and maps. Please see link:src/tupelo/csv.adoc[the Tupelo CSV docs]

=== tupelo.parse - Functions to ease parsing

TEMP TODO:  http://cloojure.github.io/tupelo/tupelo.parse.html

=== tupelo.base64 - Convert to/from base64 encoding

TEMP TODO:  see http://cloojure.github.io/tupelo/tupelo.base64.html

=== tupelo.y64 - Convert to/from the URL-safe Y64 encoding (Yahoo YUI library).

TEMP TODO:  see http://cloojure.github.io/tupelo/tupelo.y64.html

== License

Copyright © 2015 Alan Thompson. 

Distributed under the Eclipse Public License, the same as Clojure.
