= tupelo.csv

== Enhanced CSV Parsing Functions

=== Overview

The standard link:http://github.com/davidsantiago/clojure-csv[clojure-csv library] has well-tested and useful functions for parsing 
CSV (Comma Separated Value) text data, but it does not offer all of the convenience one
may wish. In `tupelo.csv` we emphasize the idomatic Clojure usage of data, using 
sequences and maps.

Typically, the first line of CSV data are the data labels which describe all of the
remaining rows of data.  The `tupelo.csv` function `parse-csv->row-maps` does exactly
what its name implies, (safely) converting the data labels into Clojure keywords and 
pairing them with each row of data to form a Clojure map.  The return value is then a
sequence of such maps. The simplest way to parse CSV data is:

[source,clojure]
----
  (parse-csv->row-maps  <csv-data-src> )
----
where <csv-data-src> is a (possibly lazy) character sequence such as a String, Java
Reader, etc. For example:

[source,clojure]
----
user=> (require '[tupelo.csv :as csv])
user=> (use     '[clojure.pprint])

user=> (def csv-str "name,  email,          phone
                     me,    me@gmail.com,   555-1234
                     you,   you@gmail.com,  999-1234" )

user=> (pprint (csv/parse-csv->row-maps ss))
({:phone "555-1234", :email "me@gmail.com", :name "me"}
 {:phone "999-1234", :email "you@gmail.com", :name "you"})
----

If the CSV data does not have data labels in the first row, the
user must supply the keyword labels using the `:labels` option, such as:

[source,clojure]
----
  (parse-csv->row-maps  <csv-data-src>  :labels [:name :email :phone] )
----

Prior to insertion into the map, each data value is processed through the function
`clojure.string/trim`.  If the user wishes to use another pre-processing function, it may
be specified using the `:data-fn` option:

[source,clojure]
----
  (parse-csv->row-maps  <csv-data-src>  :data-fn clojure.string/lower-case )
----

In general, CSV-type files sometimes use other delimiters between data fields, such as the
pipe character '|', tab character, or other choices.  If the comma is not the field
separator, the user must specify the correct character using the `:delimiter` option:

[source,clojure]
----
  (parse-csv->row-maps  <csv-data-src>  :delimiter \| )
----

The `:delimiter` option is passed directly to clojure-csv/parse-csv, as are any other
options such as `:end-of-line`, `:quote-char`, or `:strict`.  See  
link:http://github.com/davidsantiago/clojure-csv[the clojure-csv documentation] for
details.


=== Data Manipulation Functions

In some cases, the user may prefer a column-oriented output format over the default
row-oriented format. Or, one may wish to convert between row- and column-oriented formats.
In this case, the user may wish to use the `row-maps->col-vecs` function to convert between a
sequence of maps (one per row of input data) to a map of vectors, where each keyword label
is associated with a vector of the corresponding values from all rows.  Continuing the
above example:

[source,clojure]
----
user=> (def rowmap-data (csv/parse-csv->row-maps csv-str))
user=> (def colvec-data (csv/row-maps->col-vecs rowmap-data))

user=> (pprint colvec-data)
{:phone ["555-1234" "999-1234"],
 :email ["me@gmail.com" "you@gmail.com"],
 :name ["me" "you"]}
----

A corresponding function `col-vecs->row-maps` performs the opposite conversion:

[source,clojure]
----
user=> (def rowmaps2-data (csv/col-vecs->row-maps colvec-data))
user=> (pprint rowmaps2-data)
({:name "me", :email "me@gmail.com", :phone "555-1234"}
 {:name "you", :email "you@gmail.com", :phone "999-1234"})
----

Note that `row-maps->col-vecs` and its dual `col-vecs->row-maps` are very much like matrix
transform functions, and calling one on the output of the other is the identity operation.
If the user is only interested in the column-oriented data, a convenience function
`parse-cvs->col-vecs` combines the effect of `parse-csv->row-maps` and
`row-maps->col-vecs`.

[source,clojure]
----
(pprint (csv/parse-csv->col-vecs csv-str))
{:phone ["555-1234" "999-1234"],
 :email ["me@gmail.com" "you@gmail.com"],
 :name ["me" "you"]}
----
