= cooljure.csv

== Enhanced CSV Parsing Functions

=== Overview

The standard link:http://github.com/davidsantiago/clojure-csv[clojure-csv library] has well-tested and useful functions for parsing 
CSV (Comma Separated Value) text data, but it does not offer all of the convenience one
may wish. In `cooljure.csv` we emphasize the idomatic Clojure usage of data, which is
often expressed as sequence of maps.

Typically, the first line of CSV data are the data labels which describe all of the
remaining rows of data.  The `cooljure.csv` function `parse-csv->row-maps` does exactly
what its name implies, (safely) converting the data labels into Clojure keywords and 
pairing them with each row of data to form a Clojure map.  The return value is then a
sequence of such maps. The simplest way to parse CSV data is:

[source,clojure]
----
  (parse-csv->row-maps  <csv-data-src> )
----
where <csv-data-src> is a (possibly lazy) character sequence such as a Java Reader, etc.

If the CSV data does not have data labels in the first row, the
user must supply the keyword labels using the `:labels` option, such as:

[source,clojure]
----
  (parse-csv->row-maps  <csv-data-src>  :labels [:name :email :phone] )
----

Prior to insertion into the map, each data value is processed through the function
`clojure.string/trim`.  If the user wishes to use another pre-processing function, it may
be specified using the `:data-fn` option:

[source,clojure]
----
  (parse-csv->row-maps  <csv-data-src>  :data-fn clojure.string/lower-case )
----

In general, CSV-type files sometimes use other delimiters between data fields, such as the
pipe character '|', tab character, or other choices.  If the comma is not the field
separator, the user must specify the correct character using the `:delimiter` option:

[source,clojure]
----
  (parse-csv->row-maps  <csv-data-src>  :delimiter \| )
----

The `:delimiter` option is passed directly to clojure-csv/parse-csv, as are any other
options such as `:end-of-line`, `:quote-char`, or `:strict`.  See  
link:http://github.com/davidsantiago/clojure-csv[the clojure-csv documentation] for
details.


=== Data Manipulation Functions

In some cases, the user may prefer a column-oriented output format over the default
row-oriented format. Or one may wish to convert between row- and column-oriented formats.
In this case, the user may wish to use:

[source,clojure]
----
(cooljure.explicit/get m k)
----

